// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2H5Jw6DWARxuLggWq3n_7gua_xVZ22Cg',
    appId: '1:1095198071947:web:07a446e2ef3782168bc88e',
    messagingSenderId: '1095198071947',
    projectId: 'calendar-scheduler-6faae',
    authDomain: 'calendar-scheduler-6faae.firebaseapp.com',
    storageBucket: 'calendar-scheduler-6faae.appspot.com',
    measurementId: 'G-MTWQMRWMJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiQDQS9xMuiD6s9oQG6DxRRcNnYGj5uw0',
    appId: '1:1095198071947:android:dee7d538fc00ccce8bc88e',
    messagingSenderId: '1095198071947',
    projectId: 'calendar-scheduler-6faae',
    storageBucket: 'calendar-scheduler-6faae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwA8i65WzYxwXqXA2scpqM9Opjz4oc88E',
    appId: '1:1095198071947:ios:1761102f34e34cc98bc88e',
    messagingSenderId: '1095198071947',
    projectId: 'calendar-scheduler-6faae',
    storageBucket: 'calendar-scheduler-6faae.appspot.com',
    iosBundleId: 'com.example.calendarScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwA8i65WzYxwXqXA2scpqM9Opjz4oc88E',
    appId: '1:1095198071947:ios:122db3369d0e29e38bc88e',
    messagingSenderId: '1095198071947',
    projectId: 'calendar-scheduler-6faae',
    storageBucket: 'calendar-scheduler-6faae.appspot.com',
    iosBundleId: 'com.example.calendarScheduler.RunnerTests',
  );
}
